### ISSUE TITLE
Command @leavebg issue

### ISSUE THREAD

**Issue by haarenas** [dastgirp/eBG#10]
2 things about this command:

1. When you use it while you are playing a BG, it makes you leave the battle group (the guild inside bg), but it doesnt warp you to your save point. You are still able to wander around the map and atack other players.

Looking further in the code, I found out that this *if* is not executed when using the command
```
// Warp back to savepoint
if (getmapflag(strcharinfo(PC_MAP), mf_battleground))
	warp("SavePoint", 0, 0);
```
(https://github.com/dastgirp/eBG/blob/master/server/npc/eBG/bg_common.txt#L765)

When I changed **mf_battleground** to **MF_BATTLEGROUND**, surprisingly it worked and I still dont know why. Accordingly to the documentation of *getmapflag* command, the flag constants should be lower case :/
(PD:By doing this, the console/terminal popups a warning saying MF_BATTLEGROUND should be lower case. Despite of this the command DOES work)

2. Its more a suggestion than a issue. When you are queued to a BG it should make you leave the queue, but instead it only display the message "You are Not on Any Kind of BG".

I managed this by changing this:
```
OnLeaveBG:	// Replicate in bg_team_delete_pre (called when used .@leavebg/leaved bg via mapchange)	
	if (on_ebg() == false) {
		if (!.@dont_warn) {
			dispbottom(_("You are Not on Any Kind of BG"));
		}
```
to this:

```
OnLeaveBG:	// Replicate in bg_team_delete_pre (called when used .@leavebg/leaved bg via mapchange)	
	if (on_ebg() == false) {
		if (!.@dont_warn) {
			dispbottom(_("You are not on any kind of BattleGround"));
			if (queueremove(.queue[.@type], getcharid(CHAR_ID_ACCOUNT))){
				@BG_GlobalQueueID = 0;
				dispbottom(_("Leaving queue."));
			}
		}
```

**Comment by dastgirp** [comment]
@haarenas can you specify which BG does not warp out to savepoint?
Because in my test, it seems to warp me out to savepoint when using @leavebg

**Comment by dastgirp** [comment]
1) If it happens again, please mention the BG Type that was been played (CTF/Rush/etc.)
2) Implemented your suggestion : https://github.com/dastgirp/eBG/commit/97493bbb897527b0dd6d5bf7221b6fc52331ccf5
