### ISSUE TITLE
Issue with the BG Shop Points

### ISSUE THREAD

**Issue by Vaans** [dastgirp/eBG#17]
Hi, i'm having problem with the BG Shop points, the shop which enable you to bought items when you play different types of Battlegrounds.

- The NPC didn't notify you what Battleground have you played.
- The NPC always show you that you can buy -1 maximum items.
-  You can buy the item in a loop, is not discount the current points.
```
OnInit:
	setarray .bg_common, 1,         // Enable BG Shop, 1=(Item from .bg_common[1]), 2=SupplyStore, 4=BG Items, 8=WoE Items
						 Red_Potion; // The item bought by 1 point of each BG (.bg_common[0] should have 1st bit set) (Default: eBG_Red_Box
```

![imagen](https://user-images.githubusercontent.com/1972839/67227990-bda5f400-f40e-11e9-850a-dc7fbe29315d.png)

**Comment by maximus7110** [comment]
setarray .bg_common, 14
