### ISSUE TITLE
eBG_bg_rankings

### ISSUE THREAD

**Issue by tlacson7** [dastgirp/eBG#24]
sp_used, hp_potions and sp_potions records are wrong.
i tested on 2 players only.
How to test:
Each player use 1x White Potion and 1x Blue Potion inside "rush/woe" then logout to record. Upon checking the database it resulted to this:
player, sp_used, hp_potions, sp_potions
Player 1, 4227776, 1504064856, 35202984
Player 2: 4227776, 1504064856, 35191656

**Comment by dastgirp** [comment]
@tlacson7 This should be fixed in new revision
