### ISSUE TITLE
Conquest Battleground is crashing the client

### ISSUE THREAD

**Issue by cassioronchetti** [dastgirp/eBG#26]
When I was testing the Conquest Mode, I realized that there was a castle which was crashing the client. Going deep into the error, I figured out that ebg_conq03 was the cause of the issue.
You can reproduce the error by setting at bg_common to read only the casttle "ebg_conq03" which is represented by number 2 at conquest rotate:

			// Conquest have 6 Maps, ebg_conq01~ebg_conq06
			// Index is from 0~5
			$bg_conquest_rotate += 2;
			if ($bg_conquest_rotate > 2)
				$bg_conquest_rotate = 2;
			$bg_conquest_attacker = rand(1, 2);
			break;
---------------------------------------------------------------------------------------------

Then when you try to @joinbg, it will crash the game, the log of the crash is:

Module Name: C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
Time Stamp: 0x5ad44028 - Mon Apr 16 03:18:16 2018

Exception Type: 0xc0000005

0x00a5b89f	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x00a2433a	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x009f56c5	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x009f561a	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x00b0dff7	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x00b0f4f1	C:\Users\User\Documents\Servidor\Patch 2018\2018-04-18bRagexeRE_patched.exe
0x751f6359	C:\WINDOWS\System32\KERNEL32.DLL
0x77277c24	C:\WINDOWS\SYSTEM32\ntdll.dll
0x77277bf4	C:\WINDOWS\SYSTEM32\ntdll.dll

eax: 0x00000000	ebx: 0x00000001
ecx: 0x010bb020	edx: 0x0000012d
esi: 0x00000001	edi: 0x00000884
ebp: 0x0019ffec	esp: 0x0019ffe4

stack 0019ffe4 - 001a03e4
0019FFE4 : FF FF FF FF D3 8F 29 77 00 00 00 00 00 00 00 00 
0019FFF4 : C5 F3 B0 00 00 90 3D 00 00 00 00 00 41 63 74 78 
001A0004 : 20 00 00 00 01 00 00 00 38 33 00 00 DC 00 00 00 
001A0014 : 00 00 00 00 20 00 00 00 00 00 00 00 14 00 00 00 
001A0024 : 01 00 00 00 07 00 00 00 34 00 00 00 7C 01 00 00 
001A0034 : 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
001A0044 : 00 00 00 00 00 00 00 00 02 00 00 00 4E EF 26 1A 
001A0054 : 98 02 00 00 44 00 00 00 E0 02 00 00 60 02 00 00 
001A0064 : 00 00 00 00 BA 71 32 F3 40 05 00 00 4A 00 00 00 
001A0074 : 8C 05 00 00 48 03 00 00 00 00 00 00 5B 49 59 2D 
001A0084 : D4 08 00 00 32 00 00 00 08 09 00 00 00 03 00 00 
001A0094 : 00 00 00 00 CD EA CE 32 08 0C 00 00 42 00 00 00 
001A00A4 : 4C 0C 00 00 36 03 00 00 00 00 00 00 C8 5F 50 38 
001A00B4 : 84 0F 00 00 5E 00 00 00 E4 0F 00 00 68 03 00 00 
001A00C4 : 00 00 00 00 44 05 28 B1 4C 13 00 00 56 00 00 00 
001A00D4 : A4 13 00 00 98 03 00 00 10 00 00 00 09 00 00 00 

Launch Info 
00A4 00A4 00A4 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 
0000 0000 0000 0000 0000 0000 0000 0000 

Job : Novice

prontera.rsw 308 208

Renderer.cpp 700

--------------------------------------------------------------------------------
Hexed used: 20131230
I also tried using a new client: 20180418

----------------------------------------------------------------------------------

In both cases it will crash the game. Tha funny thing is that the other castles are working great.

**Comment by dastgirp** [comment]
Can you warp to schg_cas03?

**Comment by cassioronchetti** [comment]
Yes, I can warp to schg_cas03 and ebg_conq03, I only receive gravity error when joining bg.

**Comment by dastgirp** [comment]
This seems to be setwall issue which is crashing the client. 

To solve this, it might be needed to delay the setwall

**Comment by cassioronchetti** [comment]
Yes, I realized that the walls were crashing the client when I found this issue. But I didn't know how to fix it. Thank you Dastgir!
It worked! Problem Solved!
