### ISSUE TITLE
need map gat rsw 

### ISSUE THREAD

**Issue by maximus7110** [dastgirp/eBG#30]
héllo 
no map in grf ? 

 "ebg_conq01",
    "ebg_conq02",
    "ebg_conq03",
    "ebg_conq04",
    "ebg_conq05",
    "ebg_conq06",
    "ebg_ctf",
    "ebg_dom",
    "ebg_eos",
    "ebg_room",
    "ebg_rush01",
    "ebg_rush02",
    "ebg_rush03",
    "ebg_rush04",
    "ebg_sc",
    "ebg_td",
    "ebg_tti",
need rsw gat gnd please

**Comment by dastgirp** [comment]
Resmaptable clones the map, no need of files.
